#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me 
# is redirecting to another page
apt-get -y update
apt-get install -y nginx
new_string="location;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/twitter.com;\n\t}"
sed -i "s/location;/$new_string/" /etc/nginx/sites-available/default
service nginx restart
