#!/usr/bin/env bash
#nstall and configure HAproxy on my lb-01 server
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.6 -y
apt-get update
apt-get install haproxy=2.6.\* -y

#Enable HAproxy init script
service haproxy status

#configure server with the right hostnames
frontend="\nfrontend http-in\n\tbind *:80\n\tdefault_backend server\n"
backend="\nbackend server\n\tbalance roundrobin\n\tserver 109378-web-01 54.157.139.45:80 check\n\tserver 109378-web-02 52.201.220.160 check"

echo -e "$frontend$backend" >> /etc/haproxy/haproxy.cfg

#Restart HAproxy to apply changes
service haproxy restart
