#!/usr/bin/env bash
# This is a Bash script that displays lines containing the bash word
# show all processes, for all users, including those which might not have a TTY display in a user-oriented format show process hierarchy
# shellcheck disable=SC2009
ps -auxf | grep bash
