#!/usr/bin/env bash
# This is a Bash script that stops the script that displays "To infinity and beyond" indefinitely
# and saved in the file 4-to_infinity_and_beyond
kill "$(pgrep -f 4-to_infinity_and_beyond)"
