#!/usr/bin/env bash
# This is a Bash script that displays "To infinity and beyond" indefinitely
# And displays "I am invincible!!!" when receiving a SIGTERM signal
while true
do
    trap "echo I am invincible!!!" 15
    echo "To infinity and beyond"
    sleep 2
done
