#!/usr/bin/env bash
# This script is displaying:
# The content of the current directory, in a list format
# Where only the part of the name after the first dash is displayed
c_d='ls'
for c_d in *; do
    echo "$c_d" | cut -d '-' -f2
done
