#!/usr/bin/env bash
# This script is displaying information about the school file.
# use if and, else: check if the file exists and print:
# If the file exists, does not exist, is empty or not, is a regular or not.
fn='school'
if [ -e $fn ]
then
    echo "$fn file exists"
    if [ -s $fn ]
    then
        echo "$fn file is not empty"
    else
        echo "$fn file is empty"
    fi
    if [ -f $fn ]
    then
        echo "$fn is a regular file"
    fi
else
    echo "$fn file does not exist"
fi
